// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: realestate/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the realestate module's genesis state.
type GenesisState struct {
	Params            Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PropertyList      []Property     `protobuf:"bytes,2,rep,name=propertyList,proto3" json:"propertyList"`
	PropertyCount     uint64         `protobuf:"varint,3,opt,name=propertyCount,proto3" json:"propertyCount,omitempty"`
	CertificateList   []Certificate  `protobuf:"bytes,4,rep,name=certificateList,proto3" json:"certificateList"`
	CertificateCount  uint64         `protobuf:"varint,5,opt,name=certificateCount,proto3" json:"certificateCount,omitempty"`
	LockingList       []Locking      `protobuf:"bytes,6,rep,name=lockingList,proto3" json:"lockingList"`
	LockingCount      uint64         `protobuf:"varint,7,opt,name=lockingCount,proto3" json:"lockingCount,omitempty"`
	InspectionList    []Inspection   `protobuf:"bytes,8,rep,name=inspectionList,proto3" json:"inspectionList"`
	InspectionCount   uint64         `protobuf:"varint,9,opt,name=inspectionCount,proto3" json:"inspectionCount,omitempty"`
	TransferenceList  []Transference `protobuf:"bytes,10,rep,name=transferenceList,proto3" json:"transferenceList"`
	TransferenceCount uint64         `protobuf:"varint,11,opt,name=transferenceCount,proto3" json:"transferenceCount,omitempty"`
	HouseList         []House        `protobuf:"bytes,12,rep,name=houseList,proto3" json:"houseList"`
	HouseCount        uint64         `protobuf:"varint,13,opt,name=houseCount,proto3" json:"houseCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_905f352e5f4844fe, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPropertyList() []Property {
	if m != nil {
		return m.PropertyList
	}
	return nil
}

func (m *GenesisState) GetPropertyCount() uint64 {
	if m != nil {
		return m.PropertyCount
	}
	return 0
}

func (m *GenesisState) GetCertificateList() []Certificate {
	if m != nil {
		return m.CertificateList
	}
	return nil
}

func (m *GenesisState) GetCertificateCount() uint64 {
	if m != nil {
		return m.CertificateCount
	}
	return 0
}

func (m *GenesisState) GetLockingList() []Locking {
	if m != nil {
		return m.LockingList
	}
	return nil
}

func (m *GenesisState) GetLockingCount() uint64 {
	if m != nil {
		return m.LockingCount
	}
	return 0
}

func (m *GenesisState) GetInspectionList() []Inspection {
	if m != nil {
		return m.InspectionList
	}
	return nil
}

func (m *GenesisState) GetInspectionCount() uint64 {
	if m != nil {
		return m.InspectionCount
	}
	return 0
}

func (m *GenesisState) GetTransferenceList() []Transference {
	if m != nil {
		return m.TransferenceList
	}
	return nil
}

func (m *GenesisState) GetTransferenceCount() uint64 {
	if m != nil {
		return m.TransferenceCount
	}
	return 0
}

func (m *GenesisState) GetHouseList() []House {
	if m != nil {
		return m.HouseList
	}
	return nil
}

func (m *GenesisState) GetHouseCount() uint64 {
	if m != nil {
		return m.HouseCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "rafaelsousa.realestate.realestate.GenesisState")
}

func init() { proto.RegisterFile("realestate/genesis.proto", fileDescriptor_905f352e5f4844fe) }

var fileDescriptor_905f352e5f4844fe = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x1b, 0x56, 0x0a, 0xfb, 0xda, 0xb1, 0x61, 0x21, 0x08, 0x05, 0x42, 0x99, 0x38, 0x84,
	0x01, 0x89, 0x34, 0xf8, 0x05, 0xdb, 0x61, 0x20, 0x55, 0x08, 0x15, 0xb8, 0x80, 0x84, 0xe4, 0x45,
	0x6e, 0x66, 0xd1, 0xc5, 0x91, 0xed, 0x48, 0xec, 0x5f, 0xf0, 0xb3, 0x76, 0xdc, 0x91, 0xd3, 0x84,
	0xda, 0x3f, 0x82, 0xf2, 0xd9, 0x25, 0x5f, 0xdb, 0x03, 0xb9, 0xc5, 0xdf, 0x9b, 0xf7, 0x7d, 0x9f,
	0x38, 0x36, 0x84, 0x5a, 0xf0, 0x99, 0x30, 0x96, 0x5b, 0x91, 0xe6, 0xa2, 0x10, 0x46, 0x9a, 0xa4,
	0xd4, 0xca, 0x2a, 0xf6, 0x4c, 0xf3, 0x29, 0x17, 0x33, 0xa3, 0x2a, 0xc3, 0x93, 0xe6, 0x2d, 0xf2,
	0x38, 0xbc, 0x97, 0xab, 0x5c, 0xe1, 0xdb, 0x69, 0xfd, 0xe4, 0x8c, 0xc3, 0x07, 0x24, 0xb2, 0xe4,
	0x9a, 0x9f, 0xfb, 0xc4, 0xe1, 0x43, 0x2a, 0x68, 0x55, 0x0a, 0x6d, 0x2f, 0xbc, 0xf4, 0x98, 0x48,
	0x99, 0xd0, 0x56, 0x4e, 0x65, 0x56, 0x97, 0x39, 0x95, 0x42, 0xce, 0x54, 0xf6, 0x43, 0x16, 0xb9,
	0x57, 0x1e, 0x11, 0x45, 0x16, 0xa6, 0x14, 0x99, 0x95, 0xaa, 0xf0, 0xe2, 0x13, 0x22, 0x5a, 0xcd,
	0x0b, 0x33, 0x15, 0x5a, 0x14, 0xd9, 0x32, 0xf5, 0x3e, 0x91, 0xcf, 0x54, 0x65, 0xfc, 0x7c, 0xff,
	0xba, 0x07, 0x83, 0x13, 0xb7, 0x15, 0x9f, 0x6a, 0x91, 0x9d, 0x40, 0xcf, 0x7d, 0x47, 0x18, 0x8c,
	0x82, 0xb8, 0x7f, 0xf8, 0x22, 0xf9, 0xef, 0xd6, 0x24, 0x1f, 0xd1, 0x70, 0xd4, 0xbd, 0xbc, 0x7e,
	0xda, 0x99, 0x78, 0x3b, 0xfb, 0x02, 0x83, 0xe5, 0x77, 0x8f, 0xa5, 0xb1, 0xe1, 0x8d, 0xd1, 0x56,
	0xdc, 0x3f, 0x7c, 0xd9, 0x26, 0xce, 0xdb, 0x7c, 0xe0, 0x4a, 0x0c, 0x7b, 0x0e, 0x3b, 0xcb, 0xf5,
	0xb1, 0xaa, 0x0a, 0x1b, 0x6e, 0x8d, 0x82, 0xb8, 0x3b, 0x59, 0x1d, 0xb2, 0xef, 0xb0, 0x4b, 0x76,
	0x16, 0xfb, 0xbb, 0xd8, 0x9f, 0xb4, 0xe8, 0x3f, 0x6e, 0x9c, 0x1e, 0x61, 0x3d, 0x8c, 0x1d, 0xc0,
	0x1e, 0x19, 0x39, 0x90, 0x9b, 0x08, 0xb2, 0x31, 0x67, 0x13, 0xe8, 0xfb, 0xff, 0x88, 0x1c, 0x3d,
	0xe4, 0x38, 0x68, 0xc1, 0x31, 0x76, 0x2e, 0xcf, 0x40, 0x43, 0xd8, 0x3e, 0x0c, 0xfc, 0xd2, 0x75,
	0xdf, 0xc2, 0xee, 0x95, 0x19, 0xfb, 0x06, 0x77, 0x9a, 0x53, 0x82, 0xd5, 0xb7, 0xb1, 0xfa, 0x75,
	0x8b, 0xea, 0xf7, 0xff, 0x8c, 0xbe, 0x7d, 0x2d, 0x8a, 0xc5, 0xb0, 0xdb, 0x4c, 0x1c, 0xc3, 0x36,
	0x32, 0xac, 0x8f, 0x19, 0x87, 0x3d, 0x7a, 0x1e, 0x11, 0x04, 0x10, 0x24, 0x6d, 0x01, 0xf2, 0x99,
	0x58, 0x3d, 0xca, 0x46, 0x1c, 0x7b, 0x05, 0x77, 0xe9, 0xcc, 0xe1, 0xf4, 0x11, 0x67, 0x53, 0x60,
	0x63, 0xd8, 0xc6, 0x1b, 0x80, 0x24, 0x03, 0x24, 0x89, 0x5b, 0x90, 0xbc, 0xab, 0x3d, 0x1e, 0xa1,
	0x09, 0x60, 0x11, 0x00, 0x2e, 0x5c, 0xe9, 0x0e, 0x96, 0x92, 0xc9, 0xd1, 0x87, 0xcb, 0x79, 0x14,
	0x5c, 0xcd, 0xa3, 0xe0, 0xcf, 0x3c, 0x0a, 0x7e, 0x2d, 0xa2, 0xce, 0xd5, 0x22, 0xea, 0xfc, 0x5e,
	0x44, 0x9d, 0xaf, 0x6f, 0x73, 0x69, 0xcf, 0xaa, 0xd3, 0x24, 0x53, 0xe7, 0x29, 0xa9, 0x4f, 0xc9,
	0x4d, 0xfd, 0x49, 0x17, 0xf6, 0xa2, 0x14, 0xe6, 0xb4, 0x87, 0xf7, 0xf6, 0xcd, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x12, 0x44, 0xe0, 0x19, 0xcc, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HouseCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.HouseCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.HouseList) > 0 {
		for iNdEx := len(m.HouseList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HouseList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.TransferenceCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TransferenceCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.TransferenceList) > 0 {
		for iNdEx := len(m.TransferenceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TransferenceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.InspectionCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.InspectionCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.InspectionList) > 0 {
		for iNdEx := len(m.InspectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InspectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.LockingCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LockingCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.LockingList) > 0 {
		for iNdEx := len(m.LockingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LockingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.CertificateCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CertificateCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CertificateList) > 0 {
		for iNdEx := len(m.CertificateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CertificateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PropertyCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PropertyCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PropertyList) > 0 {
		for iNdEx := len(m.PropertyList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PropertyList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PropertyList) > 0 {
		for _, e := range m.PropertyList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PropertyCount != 0 {
		n += 1 + sovGenesis(uint64(m.PropertyCount))
	}
	if len(m.CertificateList) > 0 {
		for _, e := range m.CertificateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CertificateCount != 0 {
		n += 1 + sovGenesis(uint64(m.CertificateCount))
	}
	if len(m.LockingList) > 0 {
		for _, e := range m.LockingList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LockingCount != 0 {
		n += 1 + sovGenesis(uint64(m.LockingCount))
	}
	if len(m.InspectionList) > 0 {
		for _, e := range m.InspectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.InspectionCount != 0 {
		n += 1 + sovGenesis(uint64(m.InspectionCount))
	}
	if len(m.TransferenceList) > 0 {
		for _, e := range m.TransferenceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TransferenceCount != 0 {
		n += 1 + sovGenesis(uint64(m.TransferenceCount))
	}
	if len(m.HouseList) > 0 {
		for _, e := range m.HouseList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.HouseCount != 0 {
		n += 1 + sovGenesis(uint64(m.HouseCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PropertyList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PropertyList = append(m.PropertyList, Property{})
			if err := m.PropertyList[len(m.PropertyList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PropertyCount", wireType)
			}
			m.PropertyCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PropertyCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertificateList = append(m.CertificateList, Certificate{})
			if err := m.CertificateList[len(m.CertificateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateCount", wireType)
			}
			m.CertificateCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockingList = append(m.LockingList, Locking{})
			if err := m.LockingList[len(m.LockingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockingCount", wireType)
			}
			m.LockingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InspectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InspectionList = append(m.InspectionList, Inspection{})
			if err := m.InspectionList[len(m.InspectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InspectionCount", wireType)
			}
			m.InspectionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InspectionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferenceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferenceList = append(m.TransferenceList, Transference{})
			if err := m.TransferenceList[len(m.TransferenceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferenceCount", wireType)
			}
			m.TransferenceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferenceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HouseList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HouseList = append(m.HouseList, House{})
			if err := m.HouseList[len(m.HouseList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HouseCount", wireType)
			}
			m.HouseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HouseCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
